#!/bin/bash

export script_append_filenames_to_images="python3 /mnt/d/calspan1/scripts/append_filenames_to_images.py"
export script_append_text="python3 /mnt/d/calspan1/scripts/append_text.py"
export script_compress_to_png="python3 /mnt/d/calspan1/scripts/compress_to_png.py"
export script_make_video="/mnt/d/calspan1/scripts/make_video.sh"
export script_merge="python3 /mnt/d/calspan1/scripts/merge.py"
export script_range_copy="python3 /mnt/d/calspan1/scripts/range_copy.py"
export script_remove_occluded="python3 /mnt/d/calspan1/scripts/remove_occluded.py"
export script_renumber="python3 /mnt/d/calspan1/scripts/renumber.py"
export script_replicate="python3 /mnt/d/calspan1/scripts/replicate.py"
export script_train_valid_split="python3 /mnt/d/calspan1/scripts/train_valid_split.py"
export script_gen_yolov5_yaml="python3 /mnt/d/calspan1/scripts/gen_yolov5_yaml.py"
export script_clean_latex="python3 /mnt/d/calspan1/scripts/clean_latex.py"
export script_append_line="python3 /mnt/d/calspan1/scripts/append_line.py"
export script_crop_images="python3 /mnt/d/calspan1/scripts/crop_images.py"
export script_move_randomly="python3 /mnt/d/calspan1/scripts/move_randomly.py"
export script_aar_graphs="python3 /mnt/d/calspan1/scripts/aar_graphs.py"
export script_randcopy_labeled_images="python3 /mnt/d/calspan1/scripts/randcopy_labeled_images.py"